// Centralized project details data for the /projects/[id] page
// Add images (array of URLs), optional videos (array of embed URLs), description and stack

export const PROJECT_DETAILS = {
  // Mobile projects (media pulled from public/images and public/videos)
  "bobo-food": {
    id: "bobo-food",
    title: "Bobo Food: Food Ordering & Delivery App",
    description:
      "Bobo Food is a React Native food ordering and delivery app where users can browse menus, place orders, and track deliveries in real time. It includes secure authentication, OTP verification, and push notifications for order updates from confirmation to arrival.",
    images: [
      "/images/bobo.png",
      "/images/bobo2.png",
      "/images/bobo3.png",
      "/images/bobo4.png",
      "/images/bobo5.png",
      "/images/bobo6.png",
      "/images/bobo7.png",
      "/images/bobo8.png",
      "/images/bobo9.png",
      "/images/bobo10.png",
      "/images/bobo11.png",
      "/images/bobo12.png",
      "/images/bobo13.png",
      "/images/bobo14.png",
      "/images/bobo15.png",
      "/images/bobo16.png",
      "/images/bobo17.png",
      "/images/bobo18.png",
      "/images/bobo19.png",
      "/images/bobo20.png",
      "/images/bobo21.png",
      "/images/bobo22.png",
      "/images/bobo23.png",
      "/images/bobo24.png",
    ],
    videos: ["/videos/bobo.mp4"],
    stack: ["React Native", "Tailwind CSS", "Firebase", "zustand"],
    github: "https://github.com/ElnatanSamuel/deliveryapp",
  },
  finex: {
    id: "finex",
    title: "Finex – Mobile Banking & Finance App",
    description:
      "Finex is a React Native mobile banking app designed for secure and convenient financial management. Users can transfer funds, withdraw money, manage beneficiaries, send messages to support, and receive instant notifications. The app also supports mobile top-ups, currency exchange, and transaction history tracking, all within a clean and intuitive interface.",
    images: [
      "/images/banking(1).png",
      "/images/banking(2).png",
      "/images/banking(3).png",
      "/images/banking(4).png",
      "/images/banking(5).png",
      "/images/banking(6).png",
      "/images/banking(7).png",
      "/images/banking(8).png",
      "/images/banking(9).png",
      "/images/banking(10).png",
      "/images/banking(11).png",
      "/images/banking(12).png",
      "/images/banking(13).png",
      "/images/banking(14).png",
      "/images/banking(15).png",
      "/images/banking(16).png",
      "/images/banking(17).png",
      "/images/banking(18).png",
      "/images/banking(19).png",
      "/images/banking(20).png",
      "/images/banking(21).png",
      "/images/banking(22).png",
      "/images/banking(23).png",
      "/images/banking(24).png",
      "/images/banking(25).png",
      "/images/banking(26).png",
      "/images/banking(27).png",
      "/images/banking(28).png",
      "/images/banking(29).png",
    ],
    videos: ["/videos/banking.mp4"],
    stack: ["React Native", "Tailwind CSS", "Firebase", "zustand"],
    github: "https://github.com/ElnatanSamuel/finex-banking",
  },
  "easy-rider": {
    id: "easy-rider",
    title: "EasyRider – Ride-Hailing & Vehicle Booking App",
    description:
      "EasyRider is a React Native app that allows users to book taxis, cars, bicycles, or self-drive vehicles. It includes secure authentication, integrated payment processing, and real-time GPS tracking, real-time chat and call feature. Users receive instant notifications for booking confirmation, driver arrival, and trip completion.",
    images: [
      "/images/easyrider(1).png",
      "/images/easyrider(2).png",
      "/images/easyrider(3).png",
      "/images/easyrider(4).png",
      "/images/easyrider(5).png",
      "/images/easyrider(6).png",
      "/images/easyrider(7).png",
      "/images/easyrider(8).png",
      "/images/easyrider(9).png",
      "/images/easyrider(10).png",
      "/images/easyrider(11).png",
      "/images/easyrider(12).png",
      "/images/easyrider(13).png",
      "/images/easyrider(14).png",
      "/images/easyrider(15).png",
      "/images/easyrider(16).png",
      "/images/easyrider(17).png",
      "/images/easyrider(18).png",
      "/images/easyrider(19).png",
      "/images/easyrider(20).png",
      "/images/easyrider(21).png",
      "/images/easyrider(22).png",
      "/images/easyrider(23).png",
      "/images/easyrider(24).png",
      "/images/easyrider(25).png",
      "/images/easyrider(26).png",
      "/images/easyrider(27).png",
      "/images/easyrider(28).png",
      "/images/easyrider(29).png",
    ],
    videos: ["/videos/easyrider.mp4"],
    stack: ["React Native", "Tailwind CSS", "zustand"],
    github: "https://github.com/ElnatanSamuel/rideapp",
  },
  conify: {
    id: "conify",
    title: "Conify - Construction Project Management App ",
    description:
      "Conify is a mobile application designed to streamline construction project management and documentation. The app allows construction teams to track daily progress, manage resources, and generate reports efficiently. Key features include daily reporting, photo documentation, resource tracking, and phase management.",
    images: [
      "/images/conify.png",
      "/images/conify2.png",
      "/images/conify3.png",
      "/images/conify4.png",
      "/images/conify5.png",
      "/images/conify6.png",
    ],
    videos: ["/videos/conify.mp4"],
    stack: [
      "React Native",
      "Tailwind CSS",
      "TypeScript",
      "Firebase",
      "React-Redux",
      "GraphQL",
    ],
    github: "https://github.com/ElnatanSamuel/conify",
  },
};
